package com.chichumunga.satisfactory.scripts.item

enum class MinorItemGroup(val printName: String) {
  GAME_START("Game Start"),
  HUB_UPGRADE_1("HUB Upgrade 1"),
  HUB_UPGRADE_2("HUB Upgrade 2"),
  HUB_UPGRADE_3("HUB Upgrade 3"),
  HUB_UPGRADE_4("HUB Upgrade 4"),
  HUB_UPGRADE_5("HUB Upgrade 5"),
  HUB_UPGRADE_6("HUB Upgrade 6"),
  BASE_BUILDING("Base Building"),
  LOGISTICS("Logistics"),
  FIELD_RESEARCH("Field Research"),
  PART_ASSEMBLY("Part Assembly"),
  OBSTACLE_CLEARING("Obstacle Clearing"),
  JUMP_PADS("Jump Pads"),
  RESOURCE_SINK_BONUS_PROGRAM("Resource Sink Bonus Program"),
  LOGISTICS_MK_2("Logistics Mk. 2"),
  COAL_POWER("Coal Power"),
  VEHICULAR_TRANSPORT("Vehicular Transport"),
  BASIC_STEEL_PRODUCTION("Basic Steel Production"),
  IMPROVED_MELEE_COMBAT("Improved Melee Combat"),
  ADVANCED_STEEL_PRODUCTION("Advanced Steel Production"),
  HYPERTUBES("Hypertubes"),
  LOGISTICS_MK_3("Logistics Mk. 3"),
  FICSIT_BLUEPRINTS("FICSIT Blueprints"),
  OIL_PROCESSING("Oil Processing"),
  INDUSTRIAL_MANUFACTURING("Industrial Manufacturing"),
  ALTERNATIVE_FLUID_TRANSPORT("Alternative Fluid Transport"),
  GAS_MASK("Gas Mask"),
  EXPANDED_POWER_INFRASTRUCTURE("Expanded Power Infrastructure"),
  JETPACK("Jetpack"),
  MONORAIL_TRAIN_TECHNOLOGY("Monorail Train Technology"),
  PIPELINE_ENGINEERING_MK_2("Pipeline Engineering Mk. 2"),
  BAUXITE_REFINEMENT("Bauxite Refinement"),
  LOGISTICS_MK_5("Logistics Mk. 5"),
  AERONAUTICAL_ENGINEERING("Aeronautical Engineering"),
  HAZMAT_SUIT("Hazmat Suit"),
  HOVER_PACK("Hover Pack"),
  NUCLEAR_POWER("Nuclear Power"),
  ADVANCED_ALUMINUM_PRODUCTION("Advanced Aluminum Production"),
  LEADING_EDGE_PRODUCTION("Leading-edge Production"),
  PARTICLE_ENRICHMENT("Particle Enrichment"),
  MILESTONES("Milestones"),
  ALIEN_ORGANISMS("Alien Organisms"),
  MYCELIA("Mycelia"),
  NUTRIENTS("Nutrients"),
  POWER_SLUGS("Power Slugs"),
  HARD_DRIVES("Hard Drives"),
  FICSMAS("FICSMAS"),
}